### ISSUE TITLE
Script to tweet certain things on certain days

### ISSUE THREAD

**Issue by benlk** [benlk/looming_midterms#1]
This would be a separate script, added to the main cron job script but with a 10s delay so it runs after the main tweet of day.
- array of dates -> message for that date
- messages composed of reminders for filing deadlines by state if you want to run for office

Stretch goal is to get the tweet ID from the countdown script and have it be the reply-to of this tweet.

Credit to @thebestsophist

**Comment by benlk** [comment]
Doing an array isn't particularly friendly to contributors; what would be neat is a CSV that gets parsed, and the CSV itself is pulled from a Google Sheet that accepts submissions. Periodically dump the Sheet into the CSV, then use something to parse the CSV to get date, text, link.

Parts:
- [x] Google Form feeding into Google Sheet: https://docs.google.com/forms/d/e/1FAIpQLSf5gxPrlEIVNM4d_W5Pu1TwHO_1LJFY-IbTCW7FEaxM25ne0w/viewform
- [x] Google Sheet https://docs.google.com/spreadsheets/d/1Gx3KrCzldP7uYOi3lp6aZSkIZ80C_oZKsaj2CeKSBUM/edit#gid=1275143625
    - field for date in ISO 8601
    - field for text
    - field for link to the thing
- [x] thing to download list of dates of things: #4
- [ ] thing to parse list of dates of things and only keep approved items from the spreadsheet (essentially: only keep form entries that have been approved): #5
- [ ] thing to convert list of dates of things into list of tweets for dates: 18mo out, 12mo out, 6mo out, so on. #6
- [ ] thing to parse tweets-for-dates CSV to find today's messages, send each message into `t`: #7

Parsing tweets-for-dates spreadsheet sounds like https://copytext.readthedocs.io/en/stable/

Fetching the spreadsheet is gonna be more complex; might just be a manual task to run for the first few weeks.

**Comment by benlk** [comment]
Alternate plan: parse [Tyler Fisher's fork](https://github.com/democrats/election-calendar/pull/36) of https://github.com/democrats/election-calendar/tree/master/2018 using jupyter/pandas a la firstpythonnotebook.org to get the things I need, and then paste that CSV into a Google Sheet so it can be group-edited. Download spreadsheet as csv, parse tweets-for-dates, `| xargs t`
